<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>netstandard2.0</TargetFramework>
    <ConfluentKafkaVersion Condition="'$(ConfluentKafkaVersion)' == ''">1.9.2</ConfluentKafkaVersion>
    <LibrdkafkaRedistVersion Condition="'$(LibrdkafkaRedistVersion)' == ''">$(ConfluentKafkaVersion)</LibrdkafkaRedistVersion>
  </PropertyGroup>

  <ItemGroup>
    <Compile Include="Infrastructure.fs" />
    <Compile Include="FsKafka.fs" />
    <Compile Include="Monitor.fs" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="MinVer" Version="7.0.0" PrivateAssets="All" />

    <PackageReference Include="FSharp.Core" Version="4.3.4" />

    <PackageReference Include="Newtonsoft.Json" Version="13.0.1" />
    <PackageReference Include="Confluent.Kafka" Version="[$(ConfluentKafkaVersion),2.15.0]" />
    <PackageReference Include="librdkafka.redist" Version="[$(LibrdkafkaRedistVersion),2.15.0]" />
    <PackageReference Include="Serilog" Version="2.7.1" />
  </ItemGroup>

</Project>
